# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='allocated',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='in_use',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('IN_USE', 'In use'), ('ALLOCATED', 'Allocated'), ('FREE', 'Free'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
    ]
