# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20160121_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nt_account',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='in_use',
        ),
        migrations.RemoveField(
            model_name='server',
            name='kvm_portal',
        ),
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='controll_ip',
            field=models.ForeignKey(default='127.0.0.1', on_delete=django.db.models.deletion.CASCADE, related_name='ctl_servers', to='assets.IPAddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.Project'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='primary_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.IPAddress'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SHUTDOWN', 'Shutdown'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='mac_address',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='descrption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='default_password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='default_user',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='interface_port',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='operation_system',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='primary_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IPAddress'),
        ),
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.Project'),
        ),
        migrations.AlterField(
            model_name='server',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SHUTDOWN', 'Shutdown'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='server',
            name='vlan_mode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
