# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20160122_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Project'),
        ),
    ]
