# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_ipaddress_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrption',
            new_name='description',
        ),
    ]
